# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\"\x07\n\x05\x65mpty\"\x1d\n\x06status\x12\x13\n\x0bstatus_info\x18\x01 \x01(\t\"N\n\x0b\x63hat_format\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x16\n\x0ereceiving_user\x18\x02 \x01(\t\x12\x14\n\x0c\x63hat_message\x18\x03 \x01(\t\"6\n\tuser_info\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x16\n\x0ereceiving_user\x18\x02 \x01(\t2\xdf\x01\n\x11spartan_Messenger\x12\x1e\n\x08\x61\x64\x64_User\x12\n.user_info\x1a\x06.empty\x12\"\n\x0bremove_User\x12\n.user_info\x1a\x07.status\x12!\n\nget_Status\x12\n.user_info\x1a\x07.status\x12%\n\x0cpost_Message\x12\x0c.chat_format\x1a\x07.status\x12$\n\x0cget_Messages\x12\x06.empty\x1a\x0c.chat_format\x12\x16\n\x04test\x12\x06.empty\x1a\x06.emptyb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=21,
)


_STATUS = _descriptor.Descriptor(
  name='status',
  full_name='status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_info', full_name='status.status_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)


_CHAT_FORMAT = _descriptor.Descriptor(
  name='chat_format',
  full_name='chat_format',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='chat_format.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiving_user', full_name='chat_format.receiving_user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chat_message', full_name='chat_format.chat_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=132,
)


_USER_INFO = _descriptor.Descriptor(
  name='user_info',
  full_name='user_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='user_info.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiving_user', full_name='user_info.receiving_user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['status'] = _STATUS
DESCRIPTOR.message_types_by_name['chat_format'] = _CHAT_FORMAT
DESCRIPTOR.message_types_by_name['user_info'] = _USER_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:empty)
  ))
_sym_db.RegisterMessage(empty)

status = _reflection.GeneratedProtocolMessageType('status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:status)
  ))
_sym_db.RegisterMessage(status)

chat_format = _reflection.GeneratedProtocolMessageType('chat_format', (_message.Message,), dict(
  DESCRIPTOR = _CHAT_FORMAT,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat_format)
  ))
_sym_db.RegisterMessage(chat_format)

user_info = _reflection.GeneratedProtocolMessageType('user_info', (_message.Message,), dict(
  DESCRIPTOR = _USER_INFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:user_info)
  ))
_sym_db.RegisterMessage(user_info)



_SPARTAN_MESSENGER = _descriptor.ServiceDescriptor(
  name='spartan_Messenger',
  full_name='spartan_Messenger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=191,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='add_User',
    full_name='spartan_Messenger.add_User',
    index=0,
    containing_service=None,
    input_type=_USER_INFO,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remove_User',
    full_name='spartan_Messenger.remove_User',
    index=1,
    containing_service=None,
    input_type=_USER_INFO,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_Status',
    full_name='spartan_Messenger.get_Status',
    index=2,
    containing_service=None,
    input_type=_USER_INFO,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='post_Message',
    full_name='spartan_Messenger.post_Message',
    index=3,
    containing_service=None,
    input_type=_CHAT_FORMAT,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_Messages',
    full_name='spartan_Messenger.get_Messages',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CHAT_FORMAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='test',
    full_name='spartan_Messenger.test',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPARTAN_MESSENGER)

DESCRIPTOR.services_by_name['spartan_Messenger'] = _SPARTAN_MESSENGER

# @@protoc_insertion_point(module_scope)
