# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class spartan_MessengerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add_User = channel.unary_unary(
        '/spartan_Messenger/add_User',
        request_serializer=chat__pb2.user_info.SerializeToString,
        response_deserializer=chat__pb2.empty.FromString,
        )
    self.remove_User = channel.unary_unary(
        '/spartan_Messenger/remove_User',
        request_serializer=chat__pb2.user_info.SerializeToString,
        response_deserializer=chat__pb2.status.FromString,
        )
    self.get_Status = channel.unary_unary(
        '/spartan_Messenger/get_Status',
        request_serializer=chat__pb2.user_info.SerializeToString,
        response_deserializer=chat__pb2.status.FromString,
        )
    self.post_Message = channel.unary_unary(
        '/spartan_Messenger/post_Message',
        request_serializer=chat__pb2.chat_format.SerializeToString,
        response_deserializer=chat__pb2.status.FromString,
        )
    self.get_Messages = channel.unary_unary(
        '/spartan_Messenger/get_Messages',
        request_serializer=chat__pb2.empty.SerializeToString,
        response_deserializer=chat__pb2.chat_format.FromString,
        )
    self.test = channel.unary_unary(
        '/spartan_Messenger/test',
        request_serializer=chat__pb2.empty.SerializeToString,
        response_deserializer=chat__pb2.empty.FromString,
        )


class spartan_MessengerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def add_User(self, request, context):
    """service for adding a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def remove_User(self, request, context):
    """service for removing the user from the active
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_Status(self, request, context):
    """service for getting status of a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def post_Message(self, request, context):
    """service for sending a message
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_Messages(self, request, context):
    """service for receiving a message
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_spartan_MessengerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add_User': grpc.unary_unary_rpc_method_handler(
          servicer.add_User,
          request_deserializer=chat__pb2.user_info.FromString,
          response_serializer=chat__pb2.empty.SerializeToString,
      ),
      'remove_User': grpc.unary_unary_rpc_method_handler(
          servicer.remove_User,
          request_deserializer=chat__pb2.user_info.FromString,
          response_serializer=chat__pb2.status.SerializeToString,
      ),
      'get_Status': grpc.unary_unary_rpc_method_handler(
          servicer.get_Status,
          request_deserializer=chat__pb2.user_info.FromString,
          response_serializer=chat__pb2.status.SerializeToString,
      ),
      'post_Message': grpc.unary_unary_rpc_method_handler(
          servicer.post_Message,
          request_deserializer=chat__pb2.chat_format.FromString,
          response_serializer=chat__pb2.status.SerializeToString,
      ),
      'get_Messages': grpc.unary_unary_rpc_method_handler(
          servicer.get_Messages,
          request_deserializer=chat__pb2.empty.FromString,
          response_serializer=chat__pb2.chat_format.SerializeToString,
      ),
      'test': grpc.unary_unary_rpc_method_handler(
          servicer.test,
          request_deserializer=chat__pb2.empty.FromString,
          response_serializer=chat__pb2.empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spartan_Messenger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
