# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import group_chat_pb2 as group__chat__pb2


class ChatServerStub(object):
  """The chat service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.New_messege = channel.unary_stream(
        '/grpc.ChatServer/New_messege',
        request_serializer=group__chat__pb2.Message.SerializeToString,
        response_deserializer=group__chat__pb2.Message.FromString,
        )
    self.Send_messge = channel.unary_unary(
        '/grpc.ChatServer/Send_messge',
        request_serializer=group__chat__pb2.Message.SerializeToString,
        response_deserializer=group__chat__pb2.Blank.FromString,
        )
    self.New_user = channel.unary_unary(
        '/grpc.ChatServer/New_user',
        request_serializer=group__chat__pb2.User.SerializeToString,
        response_deserializer=group__chat__pb2.Blank.FromString,
        )


class ChatServerServicer(object):
  """The chat service definition.
  """

  def New_messege(self, request, context):
    """This bi-directional stream makes it possible to send and receive Notes between 2 persons
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Send_messge(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def New_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'New_messege': grpc.unary_stream_rpc_method_handler(
          servicer.New_messege,
          request_deserializer=group__chat__pb2.Message.FromString,
          response_serializer=group__chat__pb2.Message.SerializeToString,
      ),
      'Send_messge': grpc.unary_unary_rpc_method_handler(
          servicer.Send_messge,
          request_deserializer=group__chat__pb2.Message.FromString,
          response_serializer=group__chat__pb2.Blank.SerializeToString,
      ),
      'New_user': grpc.unary_unary_rpc_method_handler(
          servicer.New_user,
          request_deserializer=group__chat__pb2.User.FromString,
          response_serializer=group__chat__pb2.Blank.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.ChatServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
